const { chromium } = require('playwright');
process.env.SP_SERVE = require('path').join(__dirname, '..', '..');
const server = require('../support/hub-content-mock.js');
const R = [];
const ck = (n, c, x) => { R.push([c ? 'PASS' : 'FAIL', n, x || '']); if (!c) process.exitCode = 1; };
(async () => {
  const srv = await server.start(8211);
  const b = await chromium.launch({ args: ['--no-sandbox'] });
  const __ctx = await b.newContext({ viewport: { width: 420, height: 900 } });
  await __ctx.route("**/supabase-js@2/dist/umd/supabase.js", route => route.fulfill({ path: require('path').join(__dirname, '..', 'support', 'auth-stub.js'), contentType: 'text/javascript' }));
  const p = await __ctx.newPage();
  await p.goto('http://localhost:8211/index.html', { waitUntil: 'networkidle' });
  await p.waitForSelector('.public-hero-actions');
  const box = async sel => p.$eval(sel, n => { const r = n.getBoundingClientRect(); return { top: Math.round(r.top), height: Math.round(r.height) }; });
  const signIn = await box('[data-action="show-signin"]');
  const register = await box('[data-action="show-signup"]');
  ck('Sign In and Register are the same height', signIn.height === register.height, JSON.stringify({signIn,register}));
  ck('Sign In and Register are level (same top)', signIn.top === register.top, JSON.stringify({signIn,register}));
  console.log(R.map(([s, n, x]) => `${s}  ${n}${x ? '  -- ' + x : ''}`).join('\n'));
  await b.close(); srv.close();
  process.exit(process.exitCode || 0);
})();
